import Head from "next/head";
import { Fragment } from "react";
import Banner from "../components/home-page/Banner";
import Row from "../components/home-page/Row";
import requests from "../utils/requests";

export default function Home(props) {
    return (
        <Fragment>
            <Head>
                <title>Home | Animflix</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="relative min-h-screen max-w-[1920px] m-auto overflow-x-hidden">
                <Fragment>
                    <Banner />

                    <section className="py-[3em] md:py-[6em] space-y-10 md:space-y-[5em]">
                        <Row
                            title="Trending"
                            data={props.trendingAnime}
                            type="Card"
                        />
                        <Row
                            title="Popular"
                            data={props.popularAnime}
                            type="Card"
                        />
                        <Row
                            title="Action"
                            data={props.actionAnime}
                            type="Card"
                        />
                        <Row
                            title="Mystery"
                            data={props.mysteryAnime}
                            type="Card"
                        />
                        <Row
                            title="Comedy"
                            data={props.comedyAnime}
                            type="Card"
                        />
                        <Row
                            title="Sci-Fi"
                            data={props.scifiAnime}
                            type="Card"
                        />
                    </section>
                </Fragment>
            </main>
        </Fragment>
    );
}

export async function getServerSideProps() {
    const [
        trendingAnime,
        popularAnime,
        actionAnime,
        mysteryAnime,
        comedyAnime,
        scifiAnime,
    ] = await Promise.all([
        fetch(requests.trendingPath).then((res) => res.json()),
        fetch(requests.popularPath).then((res) => res.json()),
        fetch(requests.actionPath).then((res) => res.json()),
        fetch(requests.mysteryPath).then((res) => res.json()),
        fetch(requests.comedyPath).then((res) => res.json()),
        fetch(requests.scifiPath).then((res) => res.json()),
    ]);

    return {
        props: {
            trendingAnime: trendingAnime.results,
            popularAnime: popularAnime.results,
            actionAnime: actionAnime.results,
            mysteryAnime: mysteryAnime.results,
            comedyAnime: comedyAnime.results,
            scifiAnime: scifiAnime.results,
        },
    };
}
